[2022-12-12 05:13:47,193] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.create_task_table manual__2022-12-12T05:13:44.422813+00:00 [queued]>
[2022-12-12 05:13:47,282] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.create_task_table manual__2022-12-12T05:13:44.422813+00:00 [queued]>
[2022-12-12 05:13:47,301] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 05:13:47,309] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-12 05:13:47,311] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 05:13:47,455] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_task_table> on 2022-12-12 05:13:44.422813+00:00
[2022-12-12 05:13:47,482] {standard_task_runner.py:52} INFO - Started process 7522 to run task
[2022-12-12 05:13:47,538] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'create_task_table', 'manual__2022-12-12T05:13:44.422813+00:00', '--job-id', '1582', '--raw', '--subdir', 'DAGS_FOLDER/first-dag.py', '--cfg-path', '/tmp/tmp1jf7e6zu', '--error-file', '/tmp/tmpfp452vcj']
[2022-12-12 05:13:47,549] {standard_task_runner.py:80} INFO - Job 1582: Subtask create_task_table
[2022-12-12 05:13:48,146] {task_command.py:369} INFO - Running <TaskInstance: first_dag.create_task_table manual__2022-12-12T05:13:44.422813+00:00 [running]> on host 7e39590a7807
[2022-12-12 05:13:48,511] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=create_task_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-12T05:13:44.422813+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-12T05:13:44.422813+00:00
[2022-12-12 05:13:48,577] {base.py:68} INFO - Using connection ID 'db' for task execution.
[2022-12-12 05:13:48,608] {dbapi.py:208} INFO - Running statement: 
                create table if not exists task (
                id INT,
	            value_1 INT,
	            value_2 INT
            );
              , parameters: None
[2022-12-12 05:13:48,613] {postgres.py:94} INFO - NOTICE:  relation "task" already exists, skipping

[2022-12-12 05:13:48,635] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=create_task_table, execution_date=20221212T051344, start_date=20221212T051347, end_date=20221212T051348
[2022-12-12 05:13:48,716] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-12 05:13:49,083] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
