[2022-12-11 20:00:26,740] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.create_task_table manual__2022-12-11T20:00:02.854018+00:00 [queued]>
[2022-12-11 20:00:26,759] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.create_task_table manual__2022-12-11T20:00:02.854018+00:00 [queued]>
[2022-12-11 20:00:26,760] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 20:00:26,761] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-11 20:00:26,762] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 20:00:26,780] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_task_table> on 2022-12-11 20:00:02.854018+00:00
[2022-12-11 20:00:26,785] {standard_task_runner.py:52} INFO - Started process 5427 to run task
[2022-12-11 20:00:26,795] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'create_task_table', 'manual__2022-12-11T20:00:02.854018+00:00', '--job-id', '1331', '--raw', '--subdir', 'DAGS_FOLDER/first-dag.py', '--cfg-path', '/tmp/tmp41rn4zcm', '--error-file', '/tmp/tmpu326_5h2']
[2022-12-11 20:00:26,772] {standard_task_runner.py:80} INFO - Job 1331: Subtask create_task_table
[2022-12-11 20:00:26,876] {task_command.py:369} INFO - Running <TaskInstance: first_dag.create_task_table manual__2022-12-11T20:00:02.854018+00:00 [running]> on host 7e39590a7807
[2022-12-11 20:00:27,014] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=create_task_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-11T20:00:02.854018+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-11T20:00:02.854018+00:00
[2022-12-11 20:00:27,046] {base.py:68} INFO - Using connection ID 'db' for task execution.
[2022-12-11 20:00:27,062] {dbapi.py:208} INFO - Running statement: 
                create table if not exists task (
	            value_1 INT,
	            value_2 INT
            );
              , parameters: None
[2022-12-11 20:00:27,064] {postgres.py:94} INFO - NOTICE:  relation "task" already exists, skipping

[2022-12-11 20:00:27,085] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=create_task_table, execution_date=20221211T200002, start_date=20221211T200026, end_date=20221211T200027
[2022-12-11 20:00:27,147] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-11 20:00:27,231] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
