[2022-12-12 05:27:43,519] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.insert_data manual__2022-12-12T05:27:38.502835+00:00 [queued]>
[2022-12-12 05:27:43,564] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.insert_data manual__2022-12-12T05:27:38.502835+00:00 [queued]>
[2022-12-12 05:27:43,566] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 05:27:43,571] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-12 05:27:43,573] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 05:27:43,658] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): insert_data> on 2022-12-12 05:27:38.502835+00:00
[2022-12-12 05:27:43,684] {standard_task_runner.py:52} INFO - Started process 7873 to run task
[2022-12-12 05:27:43,702] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'insert_data', 'manual__2022-12-12T05:27:38.502835+00:00', '--job-id', '1679', '--raw', '--subdir', 'DAGS_FOLDER/first-dag.py', '--cfg-path', '/tmp/tmpocwpw7r_', '--error-file', '/tmp/tmpcskkw7ge']
[2022-12-12 05:27:43,711] {standard_task_runner.py:80} INFO - Job 1679: Subtask insert_data
[2022-12-12 05:27:43,875] {task_command.py:369} INFO - Running <TaskInstance: first_dag.insert_data manual__2022-12-12T05:27:38.502835+00:00 [running]> on host 7e39590a7807
[2022-12-12 05:27:45,244] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-12T05:27:38.502835+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-12T05:27:38.502835+00:00
[2022-12-12 05:27:45,406] {base.py:68} INFO - Using connection ID 'db' for task execution.
[2022-12-12 05:27:45,738] {logging_mixin.py:115} INFO - insert into task(value_1, value_2) VALUES (10,5
);
[2022-12-12 05:27:45,805] {logging_mixin.py:115} INFO - PostgreSQL connection is closed
[2022-12-12 05:27:45,811] {python.py:173} INFO - Done. Returned value was: None
[2022-12-12 05:27:45,929] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=insert_data, execution_date=20221212T052738, start_date=20221212T052743, end_date=20221212T052745
[2022-12-12 05:27:46,228] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-12 05:27:46,741] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
