[2022-12-11 14:09:02,987] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.generate_two_int_task scheduled__2022-12-11T14:08:00+00:00 [queued]>
[2022-12-11 14:09:03,000] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.generate_two_int_task scheduled__2022-12-11T14:08:00+00:00 [queued]>
[2022-12-11 14:09:03,001] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 14:09:03,003] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-11 14:09:03,004] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 14:09:03,023] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): generate_two_int_task> on 2022-12-11 14:08:00+00:00
[2022-12-11 14:09:03,029] {standard_task_runner.py:52} INFO - Started process 333 to run task
[2022-12-11 14:09:03,035] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'generate_two_int_task', 'scheduled__2022-12-11T14:08:00+00:00', '--job-id', '364', '--raw', '--subdir', 'DAGS_FOLDER/first-dag.py', '--cfg-path', '/tmp/tmpa1aeglsk', '--error-file', '/tmp/tmpm97yv8x2']
[2022-12-11 14:09:03,037] {standard_task_runner.py:80} INFO - Job 364: Subtask generate_two_int_task
[2022-12-11 14:09:03,136] {task_command.py:369} INFO - Running <TaskInstance: first_dag.generate_two_int_task scheduled__2022-12-11T14:08:00+00:00 [running]> on host 7e39590a7807
[2022-12-11 14:09:03,241] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=generate_two_int_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-11T14:08:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-11T14:08:00+00:00
[2022-12-11 14:09:03,263] {python.py:173} INFO - Done. Returned value was: None
[2022-12-11 14:09:03,285] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=generate_two_int_task, execution_date=20221211T140800, start_date=20221211T140902, end_date=20221211T140903
[2022-12-11 14:09:03,336] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-11 14:09:03,400] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
