[2022-12-11 20:37:54,251] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.create_task_table manual__2022-12-11T20:37:47.868656+00:00 [queued]>
[2022-12-11 20:37:54,291] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.create_task_table manual__2022-12-11T20:37:47.868656+00:00 [queued]>
[2022-12-11 20:37:54,341] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 20:37:54,342] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-11 20:37:54,344] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 20:37:54,410] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_task_table> on 2022-12-11 20:37:47.868656+00:00
[2022-12-11 20:37:54,425] {standard_task_runner.py:52} INFO - Started process 6145 to run task
[2022-12-11 20:37:54,448] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'create_task_table', 'manual__2022-12-11T20:37:47.868656+00:00', '--job-id', '1473', '--raw', '--subdir', 'DAGS_FOLDER/first-dag.py', '--cfg-path', '/tmp/tmpdwkzyhmv', '--error-file', '/tmp/tmpru97t02q']
[2022-12-11 20:37:54,465] {standard_task_runner.py:80} INFO - Job 1473: Subtask create_task_table
[2022-12-11 20:37:54,652] {task_command.py:369} INFO - Running <TaskInstance: first_dag.create_task_table manual__2022-12-11T20:37:47.868656+00:00 [running]> on host 7e39590a7807
[2022-12-11 20:37:54,902] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=create_task_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-11T20:37:47.868656+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-11T20:37:47.868656+00:00
[2022-12-11 20:37:54,992] {base.py:68} INFO - Using connection ID 'db' for task execution.
[2022-12-11 20:37:55,086] {dbapi.py:208} INFO - Running statement: 
                create table if not exists task (
	            value_1 INT,
	            value_2 INT
            );
              , parameters: None
[2022-12-11 20:37:55,096] {postgres.py:94} INFO - NOTICE:  relation "task" already exists, skipping

[2022-12-11 20:37:55,226] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=create_task_table, execution_date=20221211T203747, start_date=20221211T203754, end_date=20221211T203755
[2022-12-11 20:37:55,322] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-11 20:37:55,400] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
