[2022-12-11 14:41:02,986] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.generate_two_int_task scheduled__2022-12-11T14:40:00+00:00 [queued]>
[2022-12-11 14:41:03,001] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.generate_two_int_task scheduled__2022-12-11T14:40:00+00:00 [queued]>
[2022-12-11 14:41:03,002] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 14:41:03,004] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-11 14:41:03,004] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 14:41:03,027] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): generate_two_int_task> on 2022-12-11 14:40:00+00:00
[2022-12-11 14:41:03,035] {standard_task_runner.py:52} INFO - Started process 1220 to run task
[2022-12-11 14:41:03,047] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'generate_two_int_task', 'scheduled__2022-12-11T14:40:00+00:00', '--job-id', '579', '--raw', '--subdir', 'DAGS_FOLDER/first-dag.py', '--cfg-path', '/tmp/tmp1n7o28m2', '--error-file', '/tmp/tmp6smmgz_o']
[2022-12-11 14:41:03,049] {standard_task_runner.py:80} INFO - Job 579: Subtask generate_two_int_task
[2022-12-11 14:41:03,125] {task_command.py:369} INFO - Running <TaskInstance: first_dag.generate_two_int_task scheduled__2022-12-11T14:40:00+00:00 [running]> on host 7e39590a7807
[2022-12-11 14:41:03,230] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=generate_two_int_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-11T14:40:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-11T14:40:00+00:00
[2022-12-11 14:41:03,249] {python.py:173} INFO - Done. Returned value was: None
[2022-12-11 14:41:03,267] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=generate_two_int_task, execution_date=20221211T144000, start_date=20221211T144102, end_date=20221211T144103
[2022-12-11 14:41:03,295] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-11 14:41:03,349] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-11 14:50:02,774] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.generate_two_int_task scheduled__2022-12-11T14:40:00+00:00 [queued]>
[2022-12-11 14:50:02,790] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.generate_two_int_task scheduled__2022-12-11T14:40:00+00:00 [queued]>
[2022-12-11 14:50:02,791] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 14:50:02,792] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-11 14:50:02,793] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 14:50:02,811] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): generate_two_int_task> on 2022-12-11 14:40:00+00:00
[2022-12-11 14:50:02,819] {standard_task_runner.py:52} INFO - Started process 1478 to run task
[2022-12-11 14:50:02,829] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'generate_two_int_task', 'scheduled__2022-12-11T14:40:00+00:00', '--job-id', '634', '--raw', '--subdir', 'DAGS_FOLDER/first-dag.py', '--cfg-path', '/tmp/tmpmj03hi6f', '--error-file', '/tmp/tmpuccpi9rd']
[2022-12-11 14:50:02,833] {standard_task_runner.py:80} INFO - Job 634: Subtask generate_two_int_task
[2022-12-11 14:50:02,911] {task_command.py:369} INFO - Running <TaskInstance: first_dag.generate_two_int_task scheduled__2022-12-11T14:40:00+00:00 [running]> on host 7e39590a7807
[2022-12-11 14:50:03,039] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=generate_two_int_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-11T14:40:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-11T14:40:00+00:00
[2022-12-11 14:50:03,076] {python.py:173} INFO - Done. Returned value was: None
[2022-12-11 14:50:03,117] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=generate_two_int_task, execution_date=20221211T144000, start_date=20221211T145002, end_date=20221211T145003
[2022-12-11 14:50:03,163] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-11 14:50:03,224] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
