[2022-12-11 15:06:03,018] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.generate_two_int_task scheduled__2022-12-11T15:05:00+00:00 [queued]>
[2022-12-11 15:06:03,060] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.generate_two_int_task scheduled__2022-12-11T15:05:00+00:00 [queued]>
[2022-12-11 15:06:03,061] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 15:06:03,066] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-11 15:06:03,067] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 15:06:03,141] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): generate_two_int_task> on 2022-12-11 15:05:00+00:00
[2022-12-11 15:06:03,183] {standard_task_runner.py:52} INFO - Started process 1836 to run task
[2022-12-11 15:06:03,214] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'generate_two_int_task', 'scheduled__2022-12-11T15:05:00+00:00', '--job-id', '698', '--raw', '--subdir', 'DAGS_FOLDER/first-dag.py', '--cfg-path', '/tmp/tmpif4d73eq', '--error-file', '/tmp/tmpknxc4ks3']
[2022-12-11 15:06:03,222] {standard_task_runner.py:80} INFO - Job 698: Subtask generate_two_int_task
[2022-12-11 15:06:03,496] {task_command.py:369} INFO - Running <TaskInstance: first_dag.generate_two_int_task scheduled__2022-12-11T15:05:00+00:00 [running]> on host 7e39590a7807
[2022-12-11 15:06:03,691] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=generate_two_int_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-11T15:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-11T15:05:00+00:00
[2022-12-11 15:06:03,744] {python.py:173} INFO - Done. Returned value was: None
[2022-12-11 15:06:03,792] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=generate_two_int_task, execution_date=20221211T150500, start_date=20221211T150603, end_date=20221211T150603
[2022-12-11 15:06:03,849] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-11 15:06:04,000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
