[2022-12-12 05:14:18,107] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.insert_data manual__2022-12-12T05:13:33.076186+00:00 [queued]>
[2022-12-12 05:14:18,126] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.insert_data manual__2022-12-12T05:13:33.076186+00:00 [queued]>
[2022-12-12 05:14:18,126] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 05:14:18,127] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-12 05:14:18,128] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 05:14:18,148] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): insert_data> on 2022-12-12 05:13:33.076186+00:00
[2022-12-12 05:14:18,154] {standard_task_runner.py:52} INFO - Started process 7589 to run task
[2022-12-12 05:14:18,163] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'insert_data', 'manual__2022-12-12T05:13:33.076186+00:00', '--job-id', '1614', '--raw', '--subdir', 'DAGS_FOLDER/first-dag.py', '--cfg-path', '/tmp/tmpaggmeqpq', '--error-file', '/tmp/tmp_q2sqmml']
[2022-12-12 05:14:18,166] {standard_task_runner.py:80} INFO - Job 1614: Subtask insert_data
[2022-12-12 05:14:18,260] {task_command.py:369} INFO - Running <TaskInstance: first_dag.insert_data manual__2022-12-12T05:13:33.076186+00:00 [running]> on host 7e39590a7807
[2022-12-12 05:14:18,387] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-12T05:13:33.076186+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-12T05:13:33.076186+00:00
[2022-12-12 05:14:18,409] {base.py:68} INFO - Using connection ID 'db' for task execution.
[2022-12-12 05:14:18,434] {logging_mixin.py:115} INFO - insert into task(value_1, value_2) VALUES (5,8
);insert into task(value_1, value_2) VALUES (1,6
);insert into task(value_1, value_2) VALUES (6,7
);insert into task(value_1, value_2) VALUES (10,3
);insert into task(value_1, value_2) VALUES (10,7
);
[2022-12-12 05:14:18,438] {logging_mixin.py:115} INFO - PostgreSQL connection is closed
[2022-12-12 05:14:18,439] {python.py:173} INFO - Done. Returned value was: None
[2022-12-12 05:14:18,464] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=insert_data, execution_date=20221212T051333, start_date=20221212T051418, end_date=20221212T051418
[2022-12-12 05:14:18,495] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-12 05:14:18,547] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
