[2022-12-11 16:09:47,633] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.generate_two_int_task scheduled__2022-12-11T15:38:00+00:00 [queued]>
[2022-12-11 16:09:47,655] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.generate_two_int_task scheduled__2022-12-11T15:38:00+00:00 [queued]>
[2022-12-11 16:09:47,657] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 16:09:47,683] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-11 16:09:47,686] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 16:09:47,730] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): generate_two_int_task> on 2022-12-11 15:38:00+00:00
[2022-12-11 16:09:47,742] {standard_task_runner.py:52} INFO - Started process 2857 to run task
[2022-12-11 16:09:47,778] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'generate_two_int_task', 'scheduled__2022-12-11T15:38:00+00:00', '--job-id', '976', '--raw', '--subdir', 'DAGS_FOLDER/first-dag.py', '--cfg-path', '/tmp/tmpev5e9rlr', '--error-file', '/tmp/tmpho053n_f']
[2022-12-11 16:09:47,780] {standard_task_runner.py:80} INFO - Job 976: Subtask generate_two_int_task
[2022-12-11 16:09:47,966] {task_command.py:369} INFO - Running <TaskInstance: first_dag.generate_two_int_task scheduled__2022-12-11T15:38:00+00:00 [running]> on host 7e39590a7807
[2022-12-11 16:09:48,322] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=generate_two_int_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-11T15:38:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-11T15:38:00+00:00
[2022-12-11 16:09:48,375] {python.py:173} INFO - Done. Returned value was: None
[2022-12-11 16:09:48,416] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=generate_two_int_task, execution_date=20221211T153800, start_date=20221211T160947, end_date=20221211T160948
[2022-12-11 16:09:48,466] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-11 16:09:48,609] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
